name: gsca_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - openpyxl
  - fiona=1.9
  - ipykernel
  - rioxarray
  - xarray
  - netcdf4
  - h5netcdf
  - earthengine-api
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - tqdm
